before_install:
  - chmod +x gradlew

language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.0

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - ./gradlew build
